// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Widely.DataAccess.DataContext.Entities
{
    public partial class Appmodule
    {
        public Appmodule()
        {
            Apppermission = new HashSet<Apppermission>();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }
        public string Type { get; set; }
        public string Icon { get; set; }
        public string Path { get; set; }
        public bool? IsActive { get; set; }
        public int? Sequence { get; set; }
        public int? ParentId { get; set; }

        public virtual ICollection<Apppermission> Apppermission { get; set; }
    }
}