// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Widely.DataAccess.DataContext.Entities
{
    public partial class HomeworkCustomer
    {
        public int Id { get; set; }
        public int Type { get; set; }
        public string Name { get; set; }

        public virtual HomeworkCustomerType TypeNavigation { get; set; }
    }
}