// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Widely.DataAccess.DataContext.Entities
{
    public partial class HomeworkProduct
    {
        public HomeworkProduct()
        {
            HomeworkProductCustomer = new HashSet<HomeworkProductCustomer>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int? Qty { get; set; }

        public virtual ICollection<HomeworkProductCustomer> HomeworkProductCustomer { get; set; }
    }
}