// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Widely.DataAccess.DataContext.Entities
{
    public partial class HomeworkCustomerType
    {
        public HomeworkCustomerType()
        {
            HomeworkCustomer = new HashSet<HomeworkCustomer>();
            HomeworkProductCustomer = new HashSet<HomeworkProductCustomer>();
        }

        public int Id { get; set; }
        public string Description { get; set; }

        public virtual ICollection<HomeworkCustomer> HomeworkCustomer { get; set; }
        public virtual ICollection<HomeworkProductCustomer> HomeworkProductCustomer { get; set; }
    }
}