// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Widely.DataAccess.DataContext.Entities
{
    public partial class HomeworkProductCustomer
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int CustomerTypeId { get; set; }
        public decimal Price { get; set; }

        public virtual HomeworkCustomerType CustomerType { get; set; }
        public virtual HomeworkProduct Product { get; set; }
    }
}